### ISSUE TITLE
NO_NODE exception

### ISSUE THREAD

**Issue by khampal** [SOHU-Co/kafka-node#157]
Version of Kafka being used: 0.8.1.1
Version of kafka-node: 0.2.18

When I first try and start my application that uses kafka-node I get the following exception (which then prevents my consumer from working):

{ [NO_NODE: Exception: NO_NODE[-101]]
  code: -101,
  name: 'NO_NODE',
  path: undefined,
  message: 'Exception: NO_NODE[-101]' }

This only happens the first time the application is started (when the Kafka broker has been started). The second time the application runs it seems to work fine.

Note that with my consumers written in Java they seem to work fine first time making me think this is an issue with this package rather than my setup.

**Comment by haio** [comment]
What kind of consumer do you use?

**Comment by khampal** [comment]
It's a HighLevelConsumer

**Comment by haio** [comment]
kafka-node@0.2.19 should fix this.

**Comment by khampal** [comment]
Thanks very much!

**Comment by haio** [comment]
close.

**Comment by ismriv** [comment]
This issue is back in 0.2.26 due to https://github.com/SOHU-Co/kafka-node/commit/b702681df67be78e8d4ec258c4bb41b2dd394e49. `that.emit('error', error)` has been re-inserted and it's causing the app to crash with `NO_NODE[-101]` on startup when the consumer's groupId is new.

**Comment by haio** [comment]
@ismriv I will make a fix.

**Comment by ismriv** [comment]
Thanks a million!
