### ISSUE TITLE
Producer sending to all partitions when partition specified

### ISSUE THREAD

**Issue by ermel272** [SOHU-Co/kafka-node#451]
Hi,

I am using a Producer/Client with default partitionType to send the following message:

`[ { topic: topicName, messages: JSON.stringify(message), partition: 0 } ]`

I know that partition 0 is specified by default, however I left it in there during my troubleshooting. My understanding is that in this case the message should only be sent to partition 0. However, the actual behaviour I see is that my message is sent to each partition on the given topic. Would anyone be able to shed any light on this?

Please let me know what additional information I should provide if needed.

**Comment by hyperlink** [comment]
Make sure you're using the [Producer](/SOHU-Co/kafka-node#producer) and not the HighLevelProducer.

**Comment by ermel272** [comment]
I am currently using Producer - Here is my initialization code:

```
client = new kafka.Client(zookeeperIP + KAFKA_PORT);    
producer = new kafka.Producer(client);
````

I am attempting to debug the issue to see if any more information can be provided for you.

**Comment by sculeb** [comment]
Since I don't know how your 2 scripts look like in whole, try those 2 which work for me.

```
var kafka = require('kafka-node'),
    client = new kafka.Client('<ip>:<port>', 'producer-client'),
    producer = new kafka.Producer(client),
    payloads = [
      {
        topic: '<topic-name>',
        partition: 0,
        messages: ['a']
      }
    ];
    
producer.on('ready', () => { 
  producer.send(
    payloads,
    (err, data) => {}
  );
});

producer.on('error', err => {
  console.log(err);
});
```

and consumer:

```
var kafka = require('kafka-node'),
    client = new kafka.Client('<ip>:<port>', 'consumer-client'),
    consumer = new kafka.Consumer(
      client, 
      [
        {
          topic: '<topic-name>',
          partition: 1
        }
      ], 
      {
        autoCommit: true,
        encoding: 'utf8',
      }
    );


consumer.on('error', err => {
  console.log("error occured: " + err);
});
    
consumer.on('message', message => {
  console.log(message);
});    
```

So the producer sends to partition 0, and the consumer consumes from partition 1. When you run it, you shouldn't receive data in the consumer as you only send to partition 1. You also can play around and add a payload in the producer with a message for partition 1. Then you only should get this one in the consumer. 
I am using the latest version of kafka-node and kafka/zookeeper. If those scripts above don't work then there might be something wrong with your kafka/zk?

**Comment by ermel272** [comment]
@sculeb @hyperlink I ran a few tests with Kafka-Nodes consumer (it's worth noting that I do not use the Kafka-Node consumer to consume these Kafka messages) and saw the behaviour you indicated. When I published a message to partition 0, the Kafka-Node consumer listening on partition 1 did not pick up any messages. Since I use an external Consumer - I checked the Kafka bus to ensure the data was indeed being sent to the correct partition and it was. The problem is with the external consumer. Thank you for all the help - I appreciate it.

**Comment by Anirudh0509** [comment]
**Hey.... how does it matter if we use producer or HighLevelProducer...**
Moreover if we change the HighLevelproducer and HighLevelconsumer to producer and consumer later on.. does it have any implications...
As, I was using HighLevelProducer and HighLevelconsumer in my app... and was getting the same issue as above and later I changed it to consumer and producer still getting the same issue..
**Code--for producer**
**payloads = [
    {
      topic: 'webapp',
      partition: 0,
      messages: ['a']
    }
  ];

producer.on('ready', () => { 
producer.send(
  payloads,
  (err, data) => {}
);
});**
**Code- for consumer******
**const consumer = new Consumer(client,[
    {
        topic: "webapp",
        partition: 1
     }]
,{
    autoCommit: true,
    fetchMaxBytes: 1024 * 1024
});**
Producer has partition =0 
consumer has partition = 1
still I am getting the data.. in consumer??
Kindly help??

**Comment by Anirudh0509** [comment]
**Hey.... how does it matter if we use producer or HighLevelProducer...**
Moreover if we change the HighLevelproducer and HighLevelconsumer to producer and consumer later on.. does it have any implications...
As, I was using HighLevelProducer and HighLevelconsumer in my app... and was getting the same issue as above and later I changed it to consumer and producer still getting the same issue..
**Code--for producer**
**payloads = [
    {
      topic: 'webapp',
      partition: 0,
      messages: ['a']
    }
  ];

producer.on('ready', () => { 
producer.send(
  payloads,
  (err, data) => {}
);
});**
**Code- for consumer******
**const consumer = new Consumer(client,[
    {
        topic: "webapp",
        partition: 1
     }]
,{
    autoCommit: true,
    fetchMaxBytes: 1024 * 1024
});**
Producer has partition =0 
consumer has partition = 1
still I am getting the data.. in consumer??
Kindly help??

**Comment by hyperlink** [comment]
Don't use the `HighLevelConsumer` anymore it is deprecated by Kafka use `ConsumerGroup` or `ConsumerGroupStream`. They will automatically distribution consumption of your topic whereas regular consumer you need to specify partitions to consume manually.

**Comment by Anirudh0509** [comment]
Thanks :)
